### ISSUE TITLE
Array error

### ISSUE THREAD

**Issue by ghost** [jdasam/online_amt#1]
When I run_on_plt.py I get this error.

![image](https://user-images.githubusercontent.com/49818346/107870765-16a66080-6e7a-11eb-96a8-0e10b8e1e9a7.png)

```
PS D:\online_amt-master> python run_on_plt.py
* recording
C:\Users\Ulises\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\core\_asarray.py:102: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must 
specify 'dtype=object' when creating the ndarray.
  return array(a, dtype, copy=False, order=order)
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_on_plt.py", line 83, in <module>
    main(args.model_file)
  File "run_on_plt.py", line 75, in main
    draw_plot(q)
  File "run_on_plt.py", line 58, in draw_plot
    new_roll[:, -num_updated:] = np.asarray(updated_frames).T
ValueError: setting an array element with a sequence.
```
I would be more than grateful if you could help me =) Thanks in advance

**Comment by jdasam** [comment]
Hello,
I've found that the error occurred when the transcriber goes to sleep mode after some silence.
I didn't handle this sleep mode properly for run_on_plt.py.
I've fixed the code and updated it on the repository.

Thank you for reporting the issue.

**Comment by xMcouro** [comment]
Thank you so much! Though after the update, I get this error:
```
Traceback (most recent call last):
  File "run_on_plt.py", line 83, in <module>
    main(args.model_file)
  File "run_on_plt.py", line 68, in main
    model = load_model(model_file)
  File "D:\online_amt-master\transcribe.py", line 138, in load_model
    parameters = th.load(filename, map_location=th.device('cpu'))
  File "C:\Users\Ulises\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\serialization.py", line 595, in load   
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Ulises\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\torch\serialization.py", line 764, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
```
I'm not familiar with these technologies, so I don't know how to choose the mic input if thats related with the issue. Thanks for helping me
